on:
  push: 
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader

      - run: |
          cp .env.example .env
          sed -i 's/DB_HOST=/DB_HOST=${{ secrets.DB_HOST }}/g' .env
          sed -i 's/DB_PORT=/DB_PORT=${{ secrets.DB_PORT }}/g' .env
          sed -i 's/DB_DATABASE=/DB_DATABASE=${{ secrets.DB_DATABASE }}/g' .env
          sed -i 's/DB_USERNAME=/DB_USERNAME=${{ secrets.DB_USERNAME }}/g' .env
          sed -i 's/DB_PASSWORD=/DB_PASSWORD=${{ secrets.DB_PASSWORD }}/g' .env
        #  sed -i 's/WC_URL=/WC_URL="${{ secrets.WC_URL }}"/g' .env
        #  sed -i 's/WC_KEY=/WC_KEY=${{ secrets.WC_KEY }}/g' .env
        #  sed -i 's/WC_SECRET=/WC_SECRET=${{ secrets.WC_SECRET }}/g' .env
        #  sed -i 's/WC_VERSION=/WC_VERSION="${{ secrets.WC_VERSION }}"/g' .env

      - run: php artisan key:generate

      - uses: actions/setup-node@v2
        with:
          node-version: '18'

      - run: |
          npm install
          npm run build
          rm -rf node_modules

      - uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: './'
          target: '/var/www/tyk-crm'

      - uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
              cd /var/www/tyk-crm
              chown -R www-data:www-data .
              find . -type d -exec chmod 755 {} \;
              chmod -R 775 storage bootstrap/cache
              find . -type f -exec chmod 644 {} \;
              php artisan migrate --force
              php artisan storage:link
              php artisan optimize:clear
              php artisan config:cache
              php artisan event:cache
              php artisan route:cache
              php artisan view:cache